apiVersion: v1
kind: PodTemplate
metadata:
  name: sas-decisions-runtime-builder-kaniko-job-config
template:
  metadata:
    annotations:
      sidecar.istio.io/inject: "false"
    labels:
      workload.sas.com/class: stateless
  spec:
    tolerations:
      - key: workload.sas.com/class
        operator: Equal
        value: stateful
        effect: NoSchedule
      - key: workload.sas.com/class
        operator: Equal
        value: stateless
        effect: NoSchedule
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - stateless
        - weight: 50
          preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: NotIn
              values:
              - compute
              - cas
              - stateful
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: NotIn
              values:
              - system
    imagePullSecrets: []
    serviceAccount: sas-decisions-runtime-builder-kaniko
    serviceAccountName: sas-decisions-runtime-builder-kaniko
    securityContext:
      runAsUser: 0
    containers:
      - name: scr-builder-kaniko
        image: sas-kaniko
        args:
          - --dockerfile=/workspace/Dockerfile
          - --context=/workspace
    restartPolicy: Never
    volumes:
      - name: kaniko
        persistentVolumeClaim:
          claimName: sas-decisions-runtime-builder-kaniko
