# WARNING: Do not attempt to use this kustomization file in your deployment.
# WARNING: Kustomize Component support in CAS is being evaluated for a future release of SAS Viya.
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-backup-patch1
patch: |-
  - op: add
    path: /metadata/labels/sas.com~1backup-role
    value:
      "provider"
target:
  group: viya.sas.com
  kind: CASDeployment
  version: v1alpha1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-backup-patch2
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/containers/-
    value:
      env:
      - name: BACKUP_MOUNT_LOCATION
        value: /sasviyabackup
      - name: BACKUP_SOURCE_MOUNTS
        value: data-volume
      - name: data-volume
        value: /cas/data
      - name: NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['casoperator.sas.com/cas-env-consul-name']
      - name: CAS_NODE_TYPE
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['casoperator.sas.com/node-type']
      - name: CAS_CONTROLLER_ACTIVE
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['casoperator.sas.com/controller-active']
      - name: CAS_CFG_MODE
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['casoperator.sas.com/cas-cfg-mode']
      - name: CAS_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['casoperator.sas.com/service-name']
      envFrom:
      - configMapRef:
          name: sas-go-config
      - configMapRef:
          name: sas-shared-config
      - configMapRef:
          name: sas-java-config
      - configMapRef:
          name: sas-backup-agent-parameters
      - secretRef:
          name: sas-consul-client
      image: sas-backup-agent
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          exec:
            command: ["bash", "-c", "kill -SIGKILL $(ps -Af | grep 'backup-agent'  | grep -v grep | awk '{print $2}')"]
      resources:
        requests:
          memory: 2Gi
          cpu: 100m
        limits:
          memory: 2Gi
          cpu: 100m
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - ALL
      name: sas-backup-agent
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - name: sas-cas-backup-data
        mountPath: /sasviyabackup
      - name: cas-data-volume
        mountPath: /cas/data
      - name: cas-tmp-volume
        mountPath: /tmp
target:
  group: viya.sas.com
  kind: CASDeployment
  version: v1alpha1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-backup-patch3
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
      name: sas-cas-backup-data
      persistentVolumeClaim:
        claimName: sas-cas-backup-data
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: sas-cas-backup-data
      mountPath: /sasviyabackup
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/envFrom/-
    value:
      configMapRef:
        name: sas-restore-job-parameters
target:
  group: viya.sas.com
  kind: CASDeployment
  version: v1alpha1

