
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sas-inventory-collector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sas-inventory-collector
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sas-inventory-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sas-inventory-collector
subjects:
- kind: ServiceAccount
  name: sas-inventory-collector

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/component-name: sas-inventory-collector
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-inventory-collector
    workload.sas.com/class: stateless
  name: sas-inventory-collector
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sas.com/certificate-file-format: pem
            sas.com/kustomize-base: base
            seccomp.security.alpha.kubernetes.io/pod: runtime/default
          labels:
            app.kubernetes.io/name: sas-inventory-collector
            workload.sas.com/class: stateless
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: In
                    values:
                    - stateless
                weight: 100
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: NotIn
                    values:
                    - cas
                    - compute
                    - stateful
                weight: 50
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: NotIn
                    values:
                    - system
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution: []
              requiredDuringSchedulingIgnoredDuringExecution: []
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution: []
              requiredDuringSchedulingIgnoredDuringExecution: []
          automountServiceAccountToken: true
          containers:
          - env:
            - name: SSLREQCERT
              value: "no"
            envFrom:
            - configMapRef:
                name: sas-go-config
            - configMapRef:
                name: sas-shared-config
            - configMapRef:
                name: sas-java-config
            - configMapRef:
                name: sas-inventory-collector-parameters
            - secretRef:
                name: sas-consul-client
            image: sas-inventory-collector
            name: sas-inventory-collector
            resources:
              limits:
                cpu: 500m
                memory: 500Mi
              requests:
                cpu: 50m
                memory: 50Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add: []
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: true
            volumeMounts:
            - mountPath: /inventory
              name: inventory-volume
          imagePullSecrets: []
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
          serviceAccountName: sas-inventory-collector
          tolerations:
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: stateless
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: stateful
          volumes:
          - emptyDir: {}
            name: inventory-volume
  schedule: 0 5 31 2 *
