---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-analytics-flows
    sas.com/admin: namespace
  name: sas-analytics-flows
spec:
  routes:
  - conditions:
    - prefix: /analyticsFlows
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /analyticsFlows/
    services:
    - name: sas-analytics-flows
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /analyticsFlows/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-analytics-flows
      port: 80
    timeoutPolicy:
      response: 300s

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-analytics-gateway
    sas.com/admin: namespace
  name: sas-analytics-gateway
spec:
  routes:
  - conditions:
    - prefix: /analyticsGateway
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /analyticsGateway/
    services:
    - name: sas-analytics-gateway
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /analyticsGateway/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-analytics-gateway
      port: 80
    timeoutPolicy:
      response: 300s

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-analytics-pipelines
    sas.com/admin: namespace
  name: sas-analytics-pipelines
spec:
  routes:
  - conditions:
    - prefix: /analyticsPipelines
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /analyticsPipelines/
    services:
    - name: sas-analytics-pipelines
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /analyticsPipelines/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-analytics-pipelines
      port: 80
    timeoutPolicy:
      response: 300s

