# This block of code is for setting up Kerberos support
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-krb5-proxy-deployment-sidecar
patch: |-
  - op: add
    path: /spec/template/spec/containers/-
    value:
      env:
      - name: SAS_K8S_DEPLOYMENT_NAME
        value: "sas-krb5-proxy"
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      image: sas-krb5-proxy
      name: sas-krb5-proxy
      securityContext:
        runAsGroup: 1001
        runAsUser: 1001
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 75m
          memory: 64Mi
      volumeMounts:
      - mountPath: /opt/kerberos
        name: sas-kerberos-secrets-volume
        readOnly: true
      - mountPath: /security
        name: security
      - mountPath: /tmp
        name: krb-tmp
      - mountPath: /var/tmp
        name: var-tmp
      envFrom:
      - configMapRef:
          name: sas-servers-kerberos-sidecar-config
      - configMapRef:
          name: sas-go-config
      - configMapRef:
          name: sas-shared-config
      - configMapRef:
          name: sas-tls-config
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: sas-kerberos-secrets-volume
      secret:
        secretName: sas-servers-kerberos-secrets
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: sas-kerberos-secrets-volume
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
      readOnly: true
  - op: add
    path: /spec/template/spec/containers/0/envFrom/-
    value:
      configMapRef:
        name: sas-servers-kerberos-container-config
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      emptyDir: {}
      name: var-tmp
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      emptyDir: {}
      name: krb-tmp
target:
  kind: Deployment
  annotationSelector: sas.com/sas-kerberos-config=true
---
