apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-microanalytic-score-astores 
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20G #change this to desired capacity
  storageClassName: nfs-client #change this the desired storage class
