---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/component-name: sas-opendistro-exporter
    sas.com/kustomize-base: golang
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-opendistro-exporter
    sas.com/admin: namespace
    sas.com/deployment-base: golang
    workload.sas.com/class: stateless
  name: sas-opendistro-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-opendistro-exporter
      name: sas-opendistro-exporter
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9114"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: pem
        sas.com/component-name: sas-opendistro-exporter
        sas.com/kustomize-base: golang
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        sidecar.istio.io/inject: "false"
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-opendistro-exporter
        app.kubernetes.io/name: sas-opendistro-exporter
        name: sas-opendistro-exporter
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
                - connect
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sas-opendistro-exporter
              topologyKey: kubernetes.io/hostname
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution: []
      automountServiceAccountToken: false
      containers:
      - env:
        - name: ES_URI
          valueFrom:
            configMapKeyRef:
              key: SAS_URL_ELASTICSEARCH
              name: sas-opendistro-client-config
        - name: ES_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: sas-opendistro-sasadmin-secret
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: sas-opendistro-sasadmin-secret
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-opendistro-exporter
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        image: sas-opendistro-exporter
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: sas-opendistro-exporter
        ports:
        - containerPort: 9114
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      imagePullSecrets: []
      initContainers: []
      securityContext:
        runAsNonRoot: true
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp
---
apiVersion: v1
data:
  SAS_DU_NAME: sas-opendistro-exporter
  SAS_SERVICE_NAME: sas-opendistro-exporter
kind: ConfigMap
metadata:
  annotations:
    sas.com/component-name: sas-opendistro-exporter
  name: sas-opendistro-exporter-parameters
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/component-name: sas-opendistro-exporter
  labels:
    app.kubernetes.io/name: sas-opendistro-exporter
    sas.com/admin: namespace
    sas.com/deployment: sas-viya
  name: sas-opendistro-exporter
spec:
  ports:
  - name: http
    port: 9114
    protocol: TCP
    targetPort: 9114
  selector:
    app.kubernetes.io/name: sas-opendistro-exporter
    sas.com/deployment: sas-viya
  type: ClusterIP
