apiVersion: webinfdsvr.sas.com/v1
kind: Pgcluster
metadata:
  name: sas-crunchy-data-postgres
  annotations:
    sas.com/default-database: "true"
    sas.com/component-name: sas-crunchy-data-postgres-12
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  internal: true
  connection: {}
  database: SharedServices
  replicas: 2
  storage:
    accessmode: ReadWriteOnce
    size: 128Gi
    storageclass: nfs-client