# This file is used to increase or decrease the number
# of Redis replicas in the cluster. Changing the clusterReplicas
# will change how many replicas there are for each master.
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: redis-modify-cluster-replicas
patch: |-
    - op: replace
      path: /spec/clusterReplicas
      value: {{ REPLICA-COUNT }} # will result in REPLICA-COUNT replica nodes for each primary (stateful set)
target:
  kind: DistributedRedisCluster
  name: sas-redis-server
  version: v1alpha1
  group: redis.kun
