apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata: 
  annotations: 
    sas.com/component-name: sas-microanalytic-score
    sas.com/kustomize-base: base
  name: sas-microanalytic-score