---
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/certframe/containers/envFrom/configMapRef/name
    kind: Pgcluster
  - path: spec/certframe/initContainers/envFrom/configMapRef/name
    kind: Pgcluster
  - path: spec/certframe/volumes/configMap/name
    kind: Pgcluster
