###################################################################################
# Kustomize patch configuration to set the default and max for
# CPU requests and CPU limits. This PatchTransformer will target all PodTemplates
# with the label sas.com/template-intent=sas-launcher
# See README.md for more information.
###############################################################################
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-launcher-cpu-requests-limits
patch: |-
  - op: add
    path: /metadata/annotations/launcher.sas.com~1default-cpu-request
    value: 5
  - op: add
    path: /metadata/annotations/launcher.sas.com~1max-cpu-request
    value: 2
  - op: add
    path: /metadata/annotations/launcher.sas.com~1default-cpu-limit
    value: 5
  - op: add
    path: /metadata/annotations/launcher.sas.com~1max-cpu-limit
    value: 5
target:
  kind: PodTemplate
  labelSelector: sas.com/template-intent=sas-launcher
