apiVersion: builtin
# WARNING: Do not attempt to use this kustomization file in your deployment.
# WARNING: Kustomize Component support in CAS is being evaluated for a future release of SAS Viya.
kind: PatchTransformer
metadata:
  name: cas-apply-security-context
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/securityContext
    value:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroup: 1001
target:
  group: viya.sas.com
  kind: CASDeployment
  version: v1alpha1
