apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-opendistro-disable-security-audit-transformer
patch: |-
  - op: add
    path: /spec/config/env/-
    value: 
      name: opendistro_security.audit.enable_rest
      value: "false"
  - op: add
    path: /spec/config/env/-
    value: 
      name: opendistro_security.audit.enable_transport
      value: "false"
target:
  kind: OpenDistroCluster
