# The initial/zero phase is everything except the operators that are needed
# to shutdown the deployments before they themselves shutdown.
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: zero-scale-deployments-phase-0
patch: |-
  - op: replace
    path: /spec/replicas
    value: 0
target:
  kind: Deployment
  group: apps
  labelSelector: "!sas.com/zero-scale-phase"
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: zero-scale-pets-phase-0
patch: |-
  - op: replace
    path: /spec/replicas
    value: 0
target:
  kind: StatefulSet
  group: apps
  labelSelector: "!sas.com/zero-scale-phase"
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: zero-scale-cronjobs-phase-0
patch: |-
  - op: replace
    path: /spec/suspend
    value: true
target:
  kind: CronJob
  group: batch
  labelSelector: "!sas.com/zero-scale-phase"
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: zero-scale-casdeployments-phase-0
patch: |-
  - op: replace
    path: /spec/shutdown
    value: true
target:
  kind: CASDeployment
  group: viya.sas.com
  labelSelector: "!sas.com/zero-scale-phase"
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: zero-scale-daemonsets-phase-0
patch: |-
  - op: replace
    path: /spec/template/spec/nodeSelector
    value:
      sas.com/scale-class: "zero"
target:
  kind: DaemonSet
  group: apps
  labelSelector: "!sas.com/zero-scale-phase"
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: zero-scale-postgres-phase-0
patch: |-
  - op: replace
    path: /spec/shutdown
    value: true
target:
  group: webinfdsvr.sas.com
  kind: Pgcluster
  name: .*
  labelSelector: "!sas.com/zero-scale-phase"
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: zero-scale-opendistro-phase-0
patch: |-
  - op: replace
    path: /spec/shutdown
    value: true
target:
  kind: OpenDistroCluster
  group: opendistro.sas.com
  labelSelector: "!sas.com/zero-scale-phase"
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: zero-scale-redis-phase-0
patch: |-
  - op: replace
    path: /spec/shutdown
    value: true
target:
  kind: DistributedRedisCluster
  group: redis.kun
  labelSelector: "!sas.com/zero-scale-phase"
---