---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-deployment-operator-seccomp-remover
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: RECONCILE_TRANSFORMER
      value: default/seccomp-remove
target:
  kind: Deployment
  name: sas-deployment-operator
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: remove-seccomp-profile-from-deployment
patch: |-
  - op: replace
    path: /spec/template/metadata/annotations/seccomp.security.alpha.kubernetes.io~1pod
    value: {}
  - op: remove
    path: /spec/template/metadata/annotations/seccomp.security.alpha.kubernetes.io~1pod
target:
  kind: Deployment
