---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-opendistro-full-stack-tls-transformer
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0
    value:
      name: sas-certframe
      image: sas-certframe
      env:
      - name: KUBE_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: SAS_CERTFRAME_TOKEN_DIR
        value: /certframe-token
      - name: SAS_ADDITIONAL_CA_CERTIFICATES_DIR
        value: /customer-provided-ca-certificates
      - name: SAS_CERTIFICATE_PRIVATE_KEY_PERMISSIONS
        value: "644"
      envFrom:
      - configMapRef:
          name: sas-certframe-ingress-certificate-config
      - configMapRef:
          name: sas-certframe-user-config
      - configMapRef:
          name: sas-certframe-java-config
      volumeMounts:
      - name: certframe-token
        mountPath: /certframe-token
      - name: security
        mountPath: /security
      - name: customer-provided-ca-certificates
        mountPath: /customer-provided-ca-certificates
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "500Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /security
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts
      subPath: cacerts
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/private
      subPath: private
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: certframe-token
      secret:
        secretName: sas-certframe-token
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: security
      emptyDir: {}
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: customer-provided-ca-certificates
      configMap:
        name: sas-customer-provided-ca-certificates
  - op: add
    path: /spec/config/jvm/-
    value: -Djavax.net.ssl.trustStore=/security/trustedcerts.jks
  - op: add
    path: /spec/template/metadata/annotations/sas.com~1tls-enabled-ports
    value: all
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /usr/share/elasticsearch/config/certs
  - op: replace
    path: /spec/security
    value: 
      https: true
      certFile: certs/cert.jks
      cacertsFile: certs/trustedcerts.jks
      openIdConnectUrl: https://sas-logon-app/SASLogon/.well-known/openid-configuration
target:
  kind: OpenDistroCluster
  name: sas-opendistro
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-opendistro-client-config-full-stack-tls-transformer
patch: |-
  - op: replace
    path: /data/SAS_URL_ELASTICSEARCH
    value: https://sas-opendistro:9200
  - op: replace
    path: /data/ELASTICSEARCH_CLIENT_SSL_ENABLED
    value: "true"
target:
  kind: ConfigMap
  name: sas-opendistro-client-config
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-opendistro-exporter-full-stack-tls-transformer
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0
    value:
      name: sas-certframe
      image: sas-certframe
      env:
      - name: KUBE_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: SAS_CERTFRAME_TOKEN_DIR
        value: /certframe-token
      - name: SAS_ADDITIONAL_CA_CERTIFICATES_DIR
        value: /customer-provided-ca-certificates
      envFrom:
      - configMapRef:
          name: sas-certframe-config
      - configMapRef:
          name: sas-certframe-ingress-certificate-config
      - configMapRef:
          name: sas-certframe-user-config
      volumeMounts:
      - name: certframe-token
        mountPath: /certframe-token
      - name: security
        mountPath: /security
      - name: customer-provided-ca-certificates
        mountPath: /customer-provided-ca-certificates
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "500Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: certframe-token
      secret:
        secretName: sas-certframe-token
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: security
      emptyDir: {}
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: customer-provided-ca-certificates
      configMap:
        name: sas-customer-provided-ca-certificates
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /security
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts
      subPath: cacerts
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/private
      subPath: private
  - op: add
    path: /spec/template/spec/containers/0/envFrom/0
    value:
      configMapRef:
        name: sas-tls-config
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: ES_CA
      value: /security/trustedcerts.pem
target:
  kind: Deployment
  name: sas-opendistro-exporter
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-opendistro-operator-full-stack-tls-transformer
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0
    value:
      name: sas-certframe
      image: sas-certframe
      env:
      - name: KUBE_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: SAS_CERTFRAME_TOKEN_DIR
        value: /certframe-token
      - name: SAS_ADDITIONAL_CA_CERTIFICATES_DIR
        value: /customer-provided-ca-certificates
      envFrom:
      - configMapRef:
          name: sas-certframe-config
      - configMapRef:
          name: sas-certframe-ingress-certificate-config
      - configMapRef:
          name: sas-certframe-user-config
      volumeMounts:
      - name: certframe-token
        mountPath: /certframe-token
      - name: security
        mountPath: /security
      - name: customer-provided-ca-certificates
        mountPath: /customer-provided-ca-certificates
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "500Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: certframe-token
      secret:
        secretName: sas-certframe-token
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: security
      emptyDir: {}
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: customer-provided-ca-certificates
      configMap:
        name: sas-customer-provided-ca-certificates
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /security
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts
      subPath: cacerts
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/private
      subPath: private
  - op: add
    path: /spec/template/metadata/annotations/sas.com~1tls-enabled-ports
    value: all
  - op: replace
    path: /spec/template/metadata/annotations/prometheus.io~1scheme
    value: https
  - op: add
    path: /spec/template/spec/containers/0/envFrom/0
    value:
      configMapRef:
        name: sas-tls-config
target:
  kind: Deployment
  name: sas-opendistro-operator
