---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-base-deployment-sas-data-server-operator-full-stack-tls-transformer
patch: |-
  - op: add
    path: /spec/template/spec/initContainers/0
    value:
      name: sas-certframe
      image: sas-certframe
      env:
      - name: KUBE_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: SAS_CERTFRAME_TOKEN_DIR
        value: /certframe-token
      - name: SAS_ADDITIONAL_CA_CERTIFICATES_DIR
        value: /customer-provided-ca-certificates
      envFrom:
      - configMapRef:
          name: sas-certframe-config
      - configMapRef:
          name: sas-certframe-ingress-certificate-config
      - configMapRef:
          name: sas-certframe-user-config
      volumeMounts:
      - name: certframe-token
        mountPath: /certframe-token
      - name: security
        mountPath: /security
      - name: customer-provided-ca-certificates
        mountPath: /customer-provided-ca-certificates
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
        limits:
          memory: "500Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: certframe-token
      secret:
        secretName: sas-certframe-token
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: security
      emptyDir: {}
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: customer-provided-ca-certificates
      configMap:
        name: sas-customer-provided-ca-certificates
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /security
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts
      subPath: cacerts
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: security
      mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/private
      subPath: private
  - op: add
    path: /spec/template/metadata/annotations/sas.com~1tls-enabled-ports
    value: all
  - op: replace
    path: /spec/template/metadata/annotations/prometheus.io~1scheme
    value: https
  - op: add
    path: /spec/template/metadata/annotations/sas.com~1tls-mode
    value: full-stack
  - op: add
    path: /metadata/annotations/sas.com~1tls-mode
    value: full-stack
  - op: add
    path: /spec/template/spec/containers/0/envFrom/0
    value:
      configMapRef:
        name: sas-tls-config
target:
  kind: Deployment
  name: sas-data-server-operator
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-postgres-configmap-full-stack-tls-transformer
patch: |-
  - op: add
    path: /data/CONSUL_HTTP_ADDR
    value: https://sas-consul-server:8500
  - op: add
    path: /data/SSL_CERT_FILE
    value: /security/trustedcerts.pem
  - op: replace
    path: /data/DATABASE_SSL_ENABLED
    value: "true"
  - op: add
    path: /data/REQUESTS_CA_BUNDLE
    value: /security/trustedcerts.pem
  - op: add
    path: /data/POSTGRES_OPERATOR_SERVICE_SCHEME
    value: https
target:
  kind: ConfigMap
  name: sas-postgres-config
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-webinfdsvr-pgcluster-full-stack-tls-transformer
patch: |-
  - op: add
    path: /spec/certframe
    value:
      containers:
      - name: ignoreMe
        envFrom:
        - configMapRef:
            name: sas-tls-config
        volumeMounts:
        - name: security
          mountPath: /security
      initContainers:
      - name: sas-certframe
        image: sas-certframe
        env:
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SAS_CERTFRAME_TOKEN_DIR
          value: /certframe-token
        - name: SAS_ADDITIONAL_CA_CERTIFICATES_DIR
          value: /customer-provided-ca-certificates
        envFrom:
        - configMapRef:
            name: sas-certframe-ingress-certificate-config
        - configMapRef:
            name: sas-certframe-user-config
        - configMapRef:
            name: sas-certframe-config
        volumeMounts:
        - name: certframe-token
          mountPath: /certframe-token
        - name: security
          mountPath: /security
        - name: customer-provided-ca-certificates
          mountPath: /customer-provided-ca-certificates
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
      volumes:
      - name: certframe-token
        secret:
          secretName: sas-certframe-token
      - name: security
        emptyDir: {}
      - name: customer-provided-ca-certificates
        configMap:
          name: sas-customer-provided-ca-certificates
  - op: add
    path: /spec/connection/ssl
    value: true
target:
  kind: Pgcluster
  group: webinfdsvr.sas.com
