# This block of code is for mounting NFS persistentVolumeClaims
# to a compute session
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: compute-server-add-nfs-mount
patch: |-
  - op: add
    path: /template/spec/volumes/-
    value:
      name: sas-viya-compsrv-nfs
      nfs:
        path: /sas
        server: 10.249.6.141
  - op: add
    path: /template/spec/containers/0/volumeMounts/-
    value:
      name: sas-viya-compsrv-nfs
      mountPath: /sas
target:
  kind: PodTemplate
  version: v1
  labelSelector: sas.com/template-intent=sas-launcher
