# The following kustomize Patch transformer adds the defined credentials secret to each
# micro-service that needs it but cannot retrieve it from Consul.
#
# This file does not need to be modified unless you changed the metadata.name field of
# the credentials secret (second section).
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-pg-connection-info-to-consumers
patch: |-
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: postgres-user        # Must match name of secret containing external credentials
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: postgres-user        # Must match name of secret containing external credentials
  - op: add
    path: /spec/template/spec/containers/0/envFrom/-
    value:
      configMapRef:
        name: sas-default-pgcluster-config
target:
  group: apps
  annotationSelector: sas.com/database-consumer
