apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-postgres-configmap-cloud-sql-proxy-transformer
patch: |-
  - op: replace
    path: /spec/connection/ssl
    value: false
target:
  group: webinfdsvr.sas.com
  kind: Pgcluster
  name: .*                       # By default, target all Pgclusters. Change to a specific name to target just one.
  version: v1
