---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgreplicas.crunchydata.com
  annotations:
    sas.com/component-name: sas-crunchy-data-postgres-operator
  labels:
    sas.com/admin: "cluster-api"
spec:
  group: crunchydata.com
  names:
    kind: Pgreplica
    listKind: PgreplicaList
    plural: pgreplicas
    singular: pgreplica
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        status:
          properties:
            state: { type: string }
            message: { type: string }