#
# Note:
#   - Please refer to README.md for more information.
#   - Replace all occurrences of '{{ VIYA-DEPLOYMENT-NAMESPACE }}'
#     with the name of your valid Kubernetes namespace.
#   - This role must be applied before you onboard your first tenant.
#     For subsequent runs of the tenant job, re-apply this role
#     if the role has been dropped, or if the YAML file has changed.
#     To ensure the latest role has been applied, you may want to
#     always re-apply this role before each onboard or offboard job.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sas-tenant-job
  namespace: {{ VIYA-DEPLOYMENT-NAMESPACE }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sas-tenant-job
  namespace: {{ VIYA-DEPLOYMENT-NAMESPACE }}
rules:
  -
    apiGroups:
      - ""
      - apps
      - extensions
      - rbac.authorization.k8s.io
      - orchestration.sas.com
    resources:
      - deployments
      - configmaps
      - secrets
      - podtemplates
      - statefulsets
      - sasdeployments
      - sasdeployments/finalizers
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sas-tenant-job
  namespace: {{ VIYA-DEPLOYMENT-NAMESPACE }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sas-tenant-job
subjects:
- kind: ServiceAccount
  name: sas-tenant-job
  namespace: {{ VIYA-DEPLOYMENT-NAMESPACE }}