---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-onboard-tenant-job-generate-name-transformer
patch: |-
  - op: move
    from: /metadata/name
    path: /metadata/generateName
target:
  kind: Job
  name: sas-tenant-onboard-job-

