apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/component-name: sas-backup-copy-job
  labels:
    app.kubernetes.io/name: sas-backup-copy-job
    sas.com/job-type: "sas-backup-copy-job"
    workload.sas.com/class: stateless
  name: sas-backup-copy-job
spec:
  template:
    metadata:
      annotations:
        sas.com/certificate-file-format: pem
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        workload.sas.com/class: stateless
        sas.com/job-type: "sas-backup-copy-job"
    spec:
      securityContext:
        runAsNonRoot: true
        supplementalGroups: []
        sysctls: []
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
      containers:
      - env:
        - name: BACKUP_AGENT_TYPE
          value: BACKUP_COPY_JOB
        - name: BACKUP_MOUNT_LOCATION
          value: /sasviyabackup
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['job-name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SAS_DATA_SERVER_BACKUP_ADDITIONAL_OPTIONS
          valueFrom:
            configMapKeyRef:
              name: sas-backup-job-parameters
              key: SAS_DATA_SERVER_BACKUP_ADDITIONAL_OPTIONS
              optional: true
        - name: JOB_TIME_OUT
          valueFrom:
            configMapKeyRef:
              name: sas-backup-job-parameters
              key: JOB_TIME_OUT
              optional: true
        envFrom:
        - configMapRef:
            name: sas-go-config
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - configMapRef:
            name: sas-backup-agent-parameters
        - secretRef:
            name: sas-consul-client
        image: sas-backup-agent
        imagePullPolicy: IfNotPresent
        name: sas-backup-agent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: backup
          mountPath: /sasviyabackup
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "4Gi"
            cpu: "2"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      initContainers: []
      volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: sas-common-backup-data
      restartPolicy: Never
      serviceAccountName: sas-viya-backuprunner
      imagePullSecrets: []
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless