apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../v1beta1-crd  # overlay provided by sas-crunchy-data-postgres-operator DU saspackage/k8s/...
- ../crunchydata  # overlay provided by sas-crunchy-data-postgres-operator to internal-postgres/
- ../platform-postgres