apiVersion: orchestration.sas.com/v2beta11
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-data-server-operator
    sas.com/component-version: 21.15.7-20221212.1670882997958
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/assess: "true"
  name: assess-crunchy
spec:
  args:
  - name: namespace
    required: true
  - name: manifest
    required: true
  steps:
  - args:
    - dataserver.sas.com/crunchy-v1beta1-crds-manifest
    - "true"
    cmd: set_variable
    when: |-
      (and
        (.ManifestResource $manifest (((((.NewManifestResourcesIterationSpec).WithGroup "apps").WithVersion "v1").WithKind "Deployment").WithName "sas-crunchy-data-postgres-operator"))
        ( not (.ManifestResource $manifest ((((((.NewManifestResourcesIterationSpec).WithGroup "apiextensions.k8s.io").WithVersion "v1").WithKind "CustomResourceDefinition").WithName "pgclusters.crunchydata.com").WithAnnotationSelector "sas.com/crunchy-crd-version=v1")))
      )
  - args:
    - dataserver.sas.com/crunchy-v1-crds-cluster
    - "true"
    cmd: set_variable
    when: (.ClusterResource ((((((.NewClusterResourcesIterationSpec).WithGroup "apiextensions.k8s.io").WithVersion "v1").WithResource "customresourcedefinitions").WithName "pgclusters.crunchydata.com").WithAnnotationSelector "sas.com/crunchy-crd-version=v1"))
  - args:
    - cannot apply Crunchydata v1beta1 CRDs when Crunchydata v1 CRDs already present
    cmd: fail
    when: |-
      (and
        (.GetVariable "dataserver.sas.com/crunchy-v1beta1-crds-manifest")
        (.GetVariable "dataserver.sas.com/crunchy-v1-crds-cluster")
      )
