apiVersion: orchestration.sas.com/v2beta5
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-commonfiles
    sas.com/component-version: 1.20.38-20221105.1667651273535
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: sas-commonfiles
  name: deploy-assess-commonfiles-execute
spec:
  args:
  - name: namespace
  steps:
  - args:
    - annotate
    - --namespace
    - $namespace
    - configmap
    - sas-deploy-lifecycle-operation-variables
    - sas.com/sas-commonfiles-update=true
    cmd: kubectl
