apiVersion: orchestration.sas.com/v2beta11
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-data-server-operator
    sas.com/component-version: 21.15.7-20221212.1670882997958
  creationTimestamp: null
  labels:
    participate.lifecycle.sas.com/deploy-assess: "true"
  name: deploy-assess-dataserver
spec:
  args:
  - name: namespace
    required: true
  steps:
  - args:
    - dataserver.sas.com/internal-postgres
    - "true"
    cmd: set_variable
    when: (.ClusterResource ((((((.NewClusterResourcesIterationSpec).WithNamespace $namespace).WithGroup "apps").WithVersion "v1").WithResource "deployment").WithName "sas-crunchy-data-postgres-operator"))
