apiVersion: orchestration.sas.com/v2beta4
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-commonfiles
    sas.com/component-version: 1.20.38-20221105.1667651273535
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: sas-commonfiles
  name: deploy-pre-commonfiles-execute
spec:
  args:
  - name: namespace
  - name: timeout
  steps:
  - args:
    - delete
    - --namespace
    - $namespace
    - --wait
    - --timeout
    - $timeout
    - --ignore-not-found
    - job
    - sas-commonfiles
    cmd: kubectl
