apiVersion: orchestration.sas.com/v2beta4
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-commonfiles
    sas.com/component-version: 1.20.38-20221105.1667651273535
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: sas-commonfiles
  name: deploy-assess-commonfiles
spec:
  args:
  - name: namespace
  - name: manifest
  steps:
  - args:
    - deploy-assess-commonfiles-execute
    - --namespace
    - $namespace
    cmd: run
    when: |-
      (and
        (.ManifestResource $manifest (((((.NewManifestResourcesIterationSpec).WithGroup "batch").WithVersion "v1").WithKind "Job").WithName "sas-commonfiles"))
        (.ClusterResource ((((((.NewClusterResourcesIterationSpec).WithNamespace $namespace).WithGroup "batch").WithVersion "v1").WithResource "job").WithName "sas-commonfiles"))
        (ne
          (.Annotation "sas.com/component-version" (.ManifestResource $manifest (((((.NewManifestResourcesIterationSpec).WithGroup "batch").WithVersion "v1").WithKind "Job").WithName "sas-commonfiles")))
          (.Annotation "sas.com/component-version" (.ClusterResource ((((((.NewClusterResourcesIterationSpec).WithNamespace $namespace).WithGroup "batch").WithVersion "v1").WithResource "job").WithName "sas-commonfiles")))
        )
      )
