apiVersion: orchestration.sas.com/v2beta4
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-opendistro-operator
    sas.com/component-version: 7.17.2-20221104.1667572603049
  creationTimestamp: null
  name: deploy-assess-elasticsearch-execute
spec:
  args:
  - name: namespace
  steps:
  - args:
    - annotate
    - --namespace
    - $namespace
    - configmap
    - sas-deploy-lifecycle-operation-variables
    - sas.com/sas-opendistro-operator-update=true
    cmd: kubectl
