apiVersion: orchestration.sas.com/v2beta4
kind: LifecycleOperation
metadata:
  annotations:
    sas.com/component-name: sas-rabbitmq-server
    sas.com/component-version: 3.821003.16-20221103.1667496983589
  creationTimestamp: null
  name: deploy-pre-rabbitmq-execute
spec:
  args:
  - name: namespace
  - name: timeout
  steps:
  - args:
    - delete
    - --namespace
    - $namespace
    - --wait
    - --timeout
    - $timeout
    - --ignore-not-found
    - service
    - sas-rabbitmq-server
    cmd: kubectl
