#
# Example pghba-custom-config-transformer to add Postgres custom HBA values on your Kubernetes cluster.
#   - Please refer to README.md for more information on setting Postgres custom HBA config.
#   - Internal PostgreSQL only. 
#   - This transformer does not apply if you opted for an external PostgreSQL instance.
#
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: pghba-custom-config-transformer
patch: |-
   - op: replace
     path: /spec/pghbaconf
     value: postgres-override-pg-hba-conf
target:
  group: webinfdsvr.sas.com
  kind: Pgcluster
  name: sas-crunchy-data-postgres
  version: v1
