apiVersion: v1
kind: PersistentVolume
metadata:
  name: cas-disk-cache
spec:
  capacity:
    storage: 25Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8node-5
          - k8node-6
          - k8node-7
          - k8node-8
          - k8node-9
