---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-natural-language-conversations
    sas.com/admin: namespace
  name: sas-natural-language-conversations
spec:
  routes:
  - conditions:
    - prefix: /naturalLanguageConversations
    loadBalancerPolicy:
      strategy: Cookie
    pathRewritePolicy:
      replacePrefix:
      - replacement: /naturalLanguageConversations/
    services:
    - name: sas-natural-language-conversations
      port: 80
    timeoutPolicy:
      response: 300s
  - conditions:
    - prefix: /naturalLanguageConversations/
    loadBalancerPolicy:
      strategy: Cookie
    services:
    - name: sas-natural-language-conversations
      port: 80
    timeoutPolicy:
      response: 300s

