## Example PatchTransformer to update the seccomp annotation value.
##
## In the following code, the locations that require user specified values are indicated by a capitalized and
## hyphenated name set off by curly braces and a space at each end. You should replace this token with the
## actual value.
## Replace the curly braces, interior spaces, and the variable name.
## For instance, "{{ SECCOMP_PROFILE }}"
## should be replaced by the desired seccomp profile value
## If you use the suggested example, the correct, final syntax would be:
## value: "runtime/default"
##
##

#Update seccomp profile in all deployment pods
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: update-seccomp-profile-to-deployment
patch: |-
  - op: replace
    path: /spec/template/metadata/annotations/seccomp.security.alpha.kubernetes.io~1pod
    value: {{ SECCOMP_PROFILE }}
target:
  kind: Deployment

#Update seccomp profile in all statefulset pods
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: update-seccomp-profile-to-statefulset
patch: |-
  - op: replace
    path: /spec/template/metadata/annotations/seccomp.security.alpha.kubernetes.io~1pod
    value: {{ SECCOMP_PROFILE }}
target:
  kind: StatefulSet

#Update seccomp profile in all espconfig pods
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: update-seccomp-profile-to-espconfig
patch: |-
  - op: replace
    path: /spec/projectTemplate/deployment/spec/template/metadata/annotations/seccomp.security.alpha.kubernetes.io~1pod
    value: {{ SECCOMP_PROFILE }}
target:
  kind: ESPConfig

#Update seccomp profile in all cronjob pods
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: update-seccomp-profile-to-cronjob
patch: |-
  - op: replace
    path: /spec/jobTemplate/spec/template/metadata/annotations/seccomp.security.alpha.kubernetes.io~1pod
    value: {{ SECCOMP_PROFILE }}
target:
  kind: CronJob

#Update seccomp profile from all job pods
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: update-seccomp-profile-to-job
patch: |-
  - op: replace
    path: /spec/template/metadata/annotations/seccomp.security.alpha.kubernetes.io~1pod
    value: {{ SECCOMP_PROFILE }}
target:
  kind: Job

#Update seccomp profile in all podsTemplate
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: update-seccomp-profile-to-podTemplate
patch: |-
  - op: replace
    path: /template/metadata/annotations/seccomp.security.alpha.kubernetes.io~1pod
    value: {{ SECCOMP_PROFILE }}
target:
  kind: PodTemplate

#Update seccomp profile in all casdeployment pods
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-seccomp-annotation-override
patch: |-
  - op: add
    path: /spec/seccompProfile
    value: {{ SECCOMP-PROFILE }}

target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1