# This block of code is for disabling seccomp for CAS.
# Applying this patch will prevent the seccomp annoation
# from being added to the CAS pod.
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-disable-seccomp
patch: |-
   - op: add
     path: /spec/disableSeccomp
     value:
       true
target:
  group: viya.sas.com
  kind: CASDeployment
  # Uncomment this to apply to all CAS servers:
  name: .*
  # Uncomment this to apply to one particular named CAS server:
  #name: {{ NAME-OF-SERVER }}
  # Uncomment this to apply to the default CAS server:
  #labelSelector: "sas.com/cas-server-default"
  version: v1alpha1
