# This block of code is for overriding the default secure computing
# mode (seccomp) of 'default/runtime' for CAS. Select the desired mode
# for the seccomp profile and it will be set on the CAS Server.
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-seccomp-annotation-override
patch: |-
  - op: add
    path: /spec/seccompProfile
    value: {{ SECCOMP-PROFILE }}

target:
  group: viya.sas.com
  kind: CASDeployment
  # Uncomment this to apply to all CAS servers:
  name: .*
  # Uncomment this to apply to one particular named CAS server:
  #name: {{ NAME-OF-SERVER }}
  # Uncomment this to apply to the default CAS server:
  #labelSelector: "sas.com/cas-server-default"
  version: v1alpha1
